REDIS_PASSWORD=judge0redis
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0postgres

REDIS_URL=redis://:judge0redis@judge0-redis:6379/0
POSTGRES_HOST=judge0-db

SECRET_KEY_BASE=judge0_secret_key_base_change_me_in_production
RAILS_ENV=production
RACK_ENV=production
