# Generated by Django 6.0.6 on 2026-06-15 10:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('constraints', models.TextField(help_text='Ограничения по времени и памяти')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=16)),
                ('test_file_path', models.CharField(help_text='Путь к закрытому набору тестов', max_length=512)),
                ('total_tests', models.PositiveIntegerField()),
                ('time_limit_ms', models.PositiveIntegerField(default=1000)),
                ('memory_limit_mb', models.PositiveIntegerField(default=256)),
                ('status', models.CharField(choices=[('active', 'Активна'), ('deleted', 'Удалена')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
