# Generated by Django 6.0.6 on 2026-06-15 10:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('python', 'Python'), ('cpp', 'C++'), ('c', 'C'), ('go', 'Go'), ('java', 'Java')], max_length=16)),
                ('source_code', models.TextField()),
                ('tests_passed', models.PositiveIntegerField(default=0)),
                ('is_accepted', models.BooleanField(default=False)),
                ('verdict', models.CharField(choices=[('PENDING', 'В обработке'), ('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('CE', 'Compilation Error'), ('RE', 'Runtime Error')], default='PENDING', max_length=16)),
                ('exec_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('memory_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem')),
            ],
            options={
                'ordering': ('-submitted_at',),
            },
        ),
    ]
