# Generated by Django 5.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='error_output',
            field=models.TextField(blank=True, default=''),
        ),
    ]
